# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

# Copy the application code
COPY . .

# Install dependencies from pyproject.toml requirements
RUN pip install --no-cache-dir "httpx>=0.28.1" "mcp[cli]>=1.4.1"

# Expose port if needed (not used with stdio transport)

# Start the MCP server using the Weather application
CMD ["python", "weather.py"]
